export const CODE_LINES = [
  ["//", "// bulk_enqueue(expr, visited, wl):"],
  ["sg", "  if global(expr): return"],
  ["sv", "  if visited(expr): return"],
  ["eq", "  visited.add(expr)"],
  ["eq", "  worklist.push(expr)"],
  ["//", ""],
  ["//", "// bulk_collect(root):"],
  ["eq", "  bulk_enqueue(root)        // seed"],
  ["//", "  while worklist not empty:"],
  ["dq", "    e = worklist.pop()"],
  ["dq", "    collected.add(e)"],
  ["te", "    bulk_enqueue(e->type)"],
  ["ce", "    bulk_enqueue(e->context)"],
  ["ke", "    // VAR  → .body, .fix_expr"],
  ["ke", "    // FIX  → .args, .body"],
  ["ke", "    //         (.rec_var skipped — non-owning)"],
  ["ke", "    for c in children(e): bulk_enqueue(c)"],
  ["//", ""],
  ["//", "// free_expression_graph(root):"],
  ["//", "  all = bulk_collect(root)"],
  ["fr", "  for e in all: bulk_free_node(e)"],
];

export const FILL_CODE_LINES = [
  ["//",      "// fill_hole(hole, term):"],
  ["fh_pre",  "  assert type(hole) ≡ type(term)"],
  ["fh_pre",  "  assert valid_in_context(term)"],
  ["fh_pre",  "  if has_evar(term): assert !occurs_in(hole, term)"],
  ["//",      ""],
  ["//",      "  // 1. Structural rewrite — O(direct parents)"],
  ["fh_rw",   "  for uplink in hole->uplinks:"],
  ["fh_rw",   "    uplink.parent[rel] = term   // SET_* macro"],
  ["//",      ""],
  ["//",      "  // 2. BFS recompute has_evar — O(changed ancestors)"],
  ["fh_seed", "  queue ← { hole's parents }"],
  ["//",      "  while queue not empty:"],
  ["fh_prop", "    p = queue.dequeue()"],
  ["fh_prop", "    new = recompute_has_evar(p)"],
  ["fh_prop", "    if new ≠ p->has_evar:"],
  ["fh_prop", "      p->has_evar = new"],
  ["fh_prop", "      queue ⊕= p->uplinks   // propagate up"],
  ["fh_stop", "    // else: no change → stop here"],
  ["//",      ""],
  ["//",      "// recompute_has_evar(p):"],
  ["//",      "  if p is HOLE: return true"],
  ["//",      "  for child in p->children:"],
  ["//",      "    if child->has_evar: return true"],
  ["//",      "  return false"],
];

export const FLAT_GC_CODE_LINES = [
  ["//",      "// expression_gc_shutdown():"],
  ["//",      "  // Walk the global alloc list — O(n), one pass"],
  ["fg_init", "  expr = g_alloc_list_head"],
  ["//",      "  while expr != NULL:"],
  ["fg_free", "    next = expr->g_alloc_next"],
  ["fg_free", "    gc_free_node(expr)"],
  ["fg_free", "    expr = next"],
  ["fg_done", "  g_alloc_list_head = NULL"],
  ["//",      ""],
  ["//",      "// gc_free_node(expr):"],
  ["//",      "  free uplink list nodes"],
  ["//",      "  free tag-specific data"],
  ["//",      "    (name, branch[], args[])"],
  ["fg_free", "  free(expr)"],
];

export const CODE_HIGHLIGHT_CLASSES = {
  eq: "c-eq",
  sg: "c-sg",
  sv: "c-sv",
  dq: "c-dq",
  fr: "c-fr",
  te: "c-te",
  ce: "c-ce",
  ke: "c-ke",
  // fill_hole
  fh_pre:  "c-fh-pre",
  fh_rw:   "c-fh-rw",
  fh_seed: "c-fh-seed",
  fh_prop: "c-fh-prop",
  fh_stop: "c-fh-stop",
  fh_done: "c-fh-done",
  // flat_gc
  fg_init: "c-fg-init",
  fg_free: "c-fg-free",
  fg_done: "c-fg-done",
};
