export const SCENARIOS = {
  gc_flat: {
    description:
      "The <b>current strategy</b>: every expression is prepended to a global linked list at allocation time. At shutdown, the list is walked once linearly \u2014 freeing each node's internal data and then the node itself. No reachability analysis, no graph traversal.",
    mode: "flat_gc",
    allocOrder: ["Q", "P", "body", "g", "n", "nat"],
    root: "Q",
    viewBox: "50 10 360 275",
    nodes: {
      TYPE:  { label: "TYPE",  tag: "global", x: 350, y: 195, isGlobal: true },
      PROP:  { label: "PROP",  tag: "global", x: 350, y: 225, isGlobal: true },
      EMPTY: { label: "EMPTY", tag: "global", x: 350, y: 255, isGlobal: true },

      nat: {
        label: "nat", tag: "VAR",
        x: 130, y: 230,
        type: "TYPE", ctx: "EMPTY", children: [],
      },
      n: {
        label: "n", tag: "VAR",
        x: 110, y: 170,
        type: "nat", ctx: "nat", children: [],
      },
      g: {
        label: "g", tag: "VAR",
        x: 250, y: 170,
        type: "nat", ctx: "nat", children: [],
      },
      body: {
        label: "body", tag: "APP",
        x: 180, y: 115,
        type: "nat", ctx: "nat",
        children: [
          { to: "n", rel: "APP_FUNC" },
          { to: "g", rel: "APP_ARG" },
        ],
      },
      P: {
        label: "P", tag: "LAMBDA",
        x: 180, y: 65,
        type: "nat", ctx: "nat",
        children: [{ to: "body", rel: "LAMBDA_BODY" }],
      },
      Q: {
        label: "Q", tag: "LAMBDA",
        x: 180, y: 25,
        type: "nat", ctx: "PROP",
        children: [{ to: "P", rel: "LAMBDA_BODY" }],
      },
    },
    nonowns: [],
    uplinks: [],
  },

  gc_alt: {
    description:
      "An <b>alternative graph-traversal GC</b> (not the current strategy). Starting from an expression root, a worklist-based collector walks every owning edge to find all reachable nodes before freeing them. Illustrates challenges like shared sub-expressions and non-owning back-edges.",
    root: "rec_add",
    viewBox: "20 10 640 400",
    nodes: {
      TYPE: {
        label: "TYPE",
        tag: "global",
        x: 88,
        y: 355,
        isGlobal: true,
      },
      EMPTY: {
        label: "EMPTY",
        tag: "global",
        x: 285,
        y: 355,
        isGlobal: true,
      },
      nat: {
        label: "nat",
        tag: "VAR",
        x: 88,
        y: 235,
        type: "TYPE",
        ctx: "EMPTY",
        children: [],
      },
      fn_type: {
        label: "nat→nat→nat",
        tag: "FORALL",
        x: 285,
        y: 160,
        type: "TYPE",
        ctx: "nat",
        children: [],
      },
      rec_add: {
        label: "rec_add",
        tag: "VAR",
        x: 175,
        y: 60,
        type: "fn_type",
        ctx: "nat",
        children: [
          { to: "body_lam", rel: "VAR_BODY" },
          { to: "fix_expr", rel: "VAR_FIX_EXPR" },
        ],
      },
      body_lam: {
        label: "λn.λm.…",
        tag: "LAMBDA",
        x: 450,
        y: 60,
        type: "fn_type",
        ctx: "rec_add",
        children: [],
      },
      fix_expr: {
        label: "fix_expr",
        tag: "FIX",
        x: 500,
        y: 225,
        type: "fn_type",
        ctx: "nat",
        children: [{ to: "body_lam", rel: "FIX_BODY" }],
      },
    },
    nonowns: [
      {
        from: "fix_expr",
        to: "rec_add",
        label: "fix.rec_var (non-owning)",
      },
    ],
    uplinks: [],
  },

  // ── fill_hole: simple case ────────────────────────────────────────────────
  // P = APP(h?, g)  wrapped in Q = λx.P.
  // Filling h? with evar-free term t clears has_evar all the way to the root.
  fill_simple: {
    description: "Filling hole <b>h?</b> with a concrete term <b>t</b> that has no holes of its own. Because <b>h?</b> was the <em>only</em> hole in the tree, every ancestor loses its \u201ccontains a hole\u201d badge — the update propagates all the way to the root.",
    mode: "fill_hole",
    hole: "h",
    term: "t",
    root: "Q",
    viewBox: "30 20 400 360",
    // parentUplinks: for the BFS simulator — who are my structural parents?
    parentUplinks: {
      h: [{ parent: "P", rel: "APP_FUNC" }],
      P: [{ parent: "Q", rel: "LAMBDA_BODY" }],
      Q: [],
      t: [],
      g: [],
    },
    nodes: {
      TYPE: { label: "TYPE", tag: "global", x: 370, y: 310, isGlobal: true },
      EMPTY: { label: "EMPTY", tag: "global", x: 370, y: 350, isGlobal: true },
      PROP: { label: "PROP", tag: "global", x: 370, y: 270, isGlobal: true },

      h: {
        label: "h?",
        tag: "HOLE",
        x: 150,
        y: 260,
        type: "PROP",
        ctx: "EMPTY",
        children: [],
        initialHasEvar: true,
      },
      g: {
        label: "g",
        tag: "VAR",
        x: 310,
        y: 260,
        type: "PROP",
        ctx: "EMPTY",
        children: [],
        initialHasEvar: false,
      },
      t: {
        label: "t",
        tag: "VAR",
        x: 75,
        y: 160,
        type: "PROP",
        ctx: "EMPTY",
        children: [],
        initialHasEvar: false,
      },
      P: {
        label: "P",
        tag: "APP",
        x: 230,
        y: 160,
        type: "PROP",
        ctx: "EMPTY",
        children: [
          { to: "h", rel: "APP_FUNC", rewritesTo: "t" },
          { to: "g", rel: "APP_ARG" },
        ],
        initialHasEvar: true,
      },
      Q: {
        label: "Q",
        tag: "LAMBDA",
        x: 230,
        y: 70,
        type: "PROP",
        ctx: "EMPTY",
        children: [{ to: "P", rel: "LAMBDA_BODY" }],
        initialHasEvar: true,
      },
    },
    nonowns: [],
    uplinks: [],
  },

  fill_shared: {
    description: "<b>P</b> has <em>two</em> holes: <b>h1?</b> and <b>h2?</b>. Filling h1? with a concrete term removes one hole, but <b>P</b> still contains <b>h2?</b>. Watch how the upward walk stops at <b>P</b> \u2014 since P\u2019s badge doesn\u2019t change, its ancestors are never even visited.",
    mode: "fill_hole",
    hole: "h1",
    term: "t",
    root: "Q",
    viewBox: "30 20 420 360",
    parentUplinks: {
      h1: [{ parent: "P", rel: "APP_FUNC" }],
      h2: [{ parent: "P", rel: "APP_ARG" }],
      P: [{ parent: "Q", rel: "LAMBDA_BODY" }],
      Q: [],
      t: [],
    },
    nodes: {
      TYPE: { label: "TYPE", tag: "global", x: 390, y: 310, isGlobal: true },
      EMPTY: { label: "EMPTY", tag: "global", x: 390, y: 350, isGlobal: true },
      PROP: { label: "PROP", tag: "global", x: 390, y: 270, isGlobal: true },

      h1: {
        label: "h1?",
        tag: "HOLE",
        x: 145,
        y: 260,
        type: "PROP",
        ctx: "EMPTY",
        children: [],
        initialHasEvar: true,
      },
      h2: {
        label: "h2?",
        tag: "HOLE",
        x: 305,
        y: 260,
        type: "PROP",
        ctx: "EMPTY",
        children: [],
        initialHasEvar: true,
      },
      t: {
        label: "t",
        tag: "VAR",
        x: 70,
        y: 160,
        type: "PROP",
        ctx: "EMPTY",
        children: [],
        initialHasEvar: false,
      },
      P: {
        label: "P",
        tag: "APP",
        x: 225,
        y: 160,
        type: "PROP",
        ctx: "EMPTY",
        children: [
          { to: "h1", rel: "APP_FUNC", rewritesTo: "t" },
          { to: "h2", rel: "APP_ARG" },
        ],
        initialHasEvar: true,
      },
      Q: {
        label: "Q",
        tag: "LAMBDA",
        x: 225,
        y: 70,
        type: "PROP",
        ctx: "EMPTY",
        children: [{ to: "P", rel: "LAMBDA_BODY" }],
        initialHasEvar: true,
      },
    },
    nonowns: [],
    uplinks: [],
  },
};
